version: '3'

services:
  api-gateway:
    build: ./api-gateway
    hostname: api-gateway
    restart: always
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - postgres
    depends_on:
      - auth-svc
      - binance-svc
  
  auth-svc:
    build: ./auth-svc
    hostname: auth-svc
    restart: always
    env_file:
      - ./auth-svc/.env
    networks:
      - postgres
    depends_on:
      - postgres
  
  binance-svc:
    build: ./binance-svc
    hostname: binance-svc
    restart: always
    env_file:
      - ./binance-svc/.env
    networks:
      - postgres
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - /data/postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES=micro_auth:postgres,micro_binance:postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - postgres
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - ./.pgadmin.env

networks:
  postgres:
    driver: bridge
